// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/axon.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LifeSupport_Heartbeat_FullMethodName = "/axon.LifeSupport/Heartbeat"
)

// LifeSupportClient is the client API for LifeSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 1. THE HEARTBEAT (Solves the Orphan Process Bug)
type LifeSupportClient interface {
	// Hub sends this every 500ms. If Agent doesn't receive it, it must self-terminate.
	Heartbeat(ctx context.Context, in *Pulse, opts ...grpc.CallOption) (*PulseAck, error)
}

type lifeSupportClient struct {
	cc grpc.ClientConnInterface
}

func NewLifeSupportClient(cc grpc.ClientConnInterface) LifeSupportClient {
	return &lifeSupportClient{cc}
}

func (c *lifeSupportClient) Heartbeat(ctx context.Context, in *Pulse, opts ...grpc.CallOption) (*PulseAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PulseAck)
	err := c.cc.Invoke(ctx, LifeSupport_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LifeSupportServer is the server API for LifeSupport service.
// All implementations must embed UnimplementedLifeSupportServer
// for forward compatibility.
//
// 1. THE HEARTBEAT (Solves the Orphan Process Bug)
type LifeSupportServer interface {
	// Hub sends this every 500ms. If Agent doesn't receive it, it must self-terminate.
	Heartbeat(context.Context, *Pulse) (*PulseAck, error)
	mustEmbedUnimplementedLifeSupportServer()
}

// UnimplementedLifeSupportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifeSupportServer struct{}

func (UnimplementedLifeSupportServer) Heartbeat(context.Context, *Pulse) (*PulseAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedLifeSupportServer) mustEmbedUnimplementedLifeSupportServer() {}
func (UnimplementedLifeSupportServer) testEmbeddedByValue()                     {}

// UnsafeLifeSupportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifeSupportServer will
// result in compilation errors.
type UnsafeLifeSupportServer interface {
	mustEmbedUnimplementedLifeSupportServer()
}

func RegisterLifeSupportServer(s grpc.ServiceRegistrar, srv LifeSupportServer) {
	// If the following call panics, it indicates UnimplementedLifeSupportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LifeSupport_ServiceDesc, srv)
}

func _LifeSupport_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pulse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LifeSupportServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LifeSupport_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LifeSupportServer).Heartbeat(ctx, req.(*Pulse))
	}
	return interceptor(ctx, in, info, handler)
}

// LifeSupport_ServiceDesc is the grpc.ServiceDesc for LifeSupport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifeSupport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axon.LifeSupport",
	HandlerType: (*LifeSupportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _LifeSupport_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/axon.proto",
}

const (
	SystemControl_GetStats_FullMethodName = "/axon.SystemControl/GetStats"
)

// SystemControlClient is the client API for SystemControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 2. THE MUSCLE (Go Agent) - Skeleton for Phase 1
type SystemControlClient interface {
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStats, error)
}

type systemControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemControlClient(cc grpc.ClientConnInterface) SystemControlClient {
	return &systemControlClient{cc}
}

func (c *systemControlClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStats)
	err := c.cc.Invoke(ctx, SystemControl_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemControlServer is the server API for SystemControl service.
// All implementations must embed UnimplementedSystemControlServer
// for forward compatibility.
//
// 2. THE MUSCLE (Go Agent) - Skeleton for Phase 1
type SystemControlServer interface {
	GetStats(context.Context, *Empty) (*SystemStats, error)
	mustEmbedUnimplementedSystemControlServer()
}

// UnimplementedSystemControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSystemControlServer struct{}

func (UnimplementedSystemControlServer) GetStats(context.Context, *Empty) (*SystemStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSystemControlServer) mustEmbedUnimplementedSystemControlServer() {}
func (UnimplementedSystemControlServer) testEmbeddedByValue()                       {}

// UnsafeSystemControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemControlServer will
// result in compilation errors.
type UnsafeSystemControlServer interface {
	mustEmbedUnimplementedSystemControlServer()
}

func RegisterSystemControlServer(s grpc.ServiceRegistrar, srv SystemControlServer) {
	// If the following call panics, it indicates UnimplementedSystemControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SystemControl_ServiceDesc, srv)
}

func _SystemControl_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemControlServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SystemControl_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemControlServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemControl_ServiceDesc is the grpc.ServiceDesc for SystemControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axon.SystemControl",
	HandlerType: (*SystemControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _SystemControl_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/axon.proto",
}
