// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/axon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pulse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ALIVE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pulse) Reset() {
	*x = Pulse{}
	mi := &file_proto_axon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pulse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pulse) ProtoMessage() {}

func (x *Pulse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pulse.ProtoReflect.Descriptor instead.
func (*Pulse) Descriptor() ([]byte, []int) {
	return file_proto_axon_proto_rawDescGZIP(), []int{0}
}

func (x *Pulse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Pulse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PulseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PulseAck) Reset() {
	*x = PulseAck{}
	mi := &file_proto_axon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PulseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PulseAck) ProtoMessage() {}

func (x *PulseAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PulseAck.ProtoReflect.Descriptor instead.
func (*PulseAck) Descriptor() ([]byte, []int) {
	return file_proto_axon_proto_rawDescGZIP(), []int{1}
}

func (x *PulseAck) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_axon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_axon_proto_rawDescGZIP(), []int{2}
}

type SystemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float32                `protobuf:"fixed32,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,2,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	Uptime        float32                `protobuf:"fixed32,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_proto_axon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_axon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_proto_axon_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStats) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemStats) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *SystemStats) GetUptime() float32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

var File_proto_axon_proto protoreflect.FileDescriptor

const file_proto_axon_proto_rawDesc = "" +
	"\n" +
	"\x10proto/axon.proto\x12\x04axon\"=\n" +
	"\x05Pulse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\" \n" +
	"\bPulseAck\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\"\a\n" +
	"\x05Empty\"_\n" +
	"\vSystemStats\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x02 \x01(\x02R\bramUsage\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x02R\x06uptime27\n" +
	"\vLifeSupport\x12(\n" +
	"\tHeartbeat\x12\v.axon.Pulse\x1a\x0e.axon.PulseAck2;\n" +
	"\rSystemControl\x12*\n" +
	"\bGetStats\x12\v.axon.Empty\x1a\x11.axon.SystemStatsB\x12Z\x10axon-agent/protob\x06proto3"

var (
	file_proto_axon_proto_rawDescOnce sync.Once
	file_proto_axon_proto_rawDescData []byte
)

func file_proto_axon_proto_rawDescGZIP() []byte {
	file_proto_axon_proto_rawDescOnce.Do(func() {
		file_proto_axon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_axon_proto_rawDesc), len(file_proto_axon_proto_rawDesc)))
	})
	return file_proto_axon_proto_rawDescData
}

var file_proto_axon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_axon_proto_goTypes = []any{
	(*Pulse)(nil),       // 0: axon.Pulse
	(*PulseAck)(nil),    // 1: axon.PulseAck
	(*Empty)(nil),       // 2: axon.Empty
	(*SystemStats)(nil), // 3: axon.SystemStats
}
var file_proto_axon_proto_depIdxs = []int32{
	0, // 0: axon.LifeSupport.Heartbeat:input_type -> axon.Pulse
	2, // 1: axon.SystemControl.GetStats:input_type -> axon.Empty
	1, // 2: axon.LifeSupport.Heartbeat:output_type -> axon.PulseAck
	3, // 3: axon.SystemControl.GetStats:output_type -> axon.SystemStats
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_axon_proto_init() }
func file_proto_axon_proto_init() {
	if File_proto_axon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_axon_proto_rawDesc), len(file_proto_axon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_axon_proto_goTypes,
		DependencyIndexes: file_proto_axon_proto_depIdxs,
		MessageInfos:      file_proto_axon_proto_msgTypes,
	}.Build()
	File_proto_axon_proto = out.File
	file_proto_axon_proto_goTypes = nil
	file_proto_axon_proto_depIdxs = nil
}
